"""Mathematical state models for the spacetime-symmetry animations.

Coordinates use the square ``[-1, 1) x [-1, 1)``.  Time is normalized to
``R/Z``.  Keeping the state construction separate from rasterization makes the
group laws testable without comparing anti-aliased pixels.
"""

from __future__ import annotations

from dataclasses import dataclass
import math
from typing import Callable, Sequence


TAU = 2.0 * math.pi


@dataclass(frozen=True)
class MotifState:
    """Pose and color of one asymmetric motif."""

    orbit: int
    x: float
    y: float
    angle: float
    scale: float
    color: int
    chirality: int = 1
    glow: float = 0.5
    glyph: str = "kite"


@dataclass(frozen=True)
class SymmetrySpec:
    """A finite spacetime example and its color representation."""

    key: str
    title: str
    sampling_order: int
    phase_shift: float
    spatial_action: str
    color_permutation: tuple[int, ...]
    state_function: Callable[[float], tuple[MotifState, ...]]
    temporal_action: str = "phase translation"


def wrap_phase(value: float) -> float:
    return value % 1.0


def wrap_coordinate(value: float) -> float:
    """Wrap a coordinate onto the spatial circle represented by [-1, 1)."""

    return (value + 1.0) % 2.0 - 1.0


def _seed_pose(phase: float) -> tuple[float, float, float, float]:
    """A generic periodic, chiral motion reused across the orbit sums."""

    a = TAU * wrap_phase(phase)
    local_x = 0.075 * math.cos(a) + 0.018 * math.cos(2.0 * a + 0.4)
    local_y = 0.105 * math.sin(a) + 0.022 * math.sin(2.0 * a - 0.3)
    angle = 0.62 * math.sin(a + 0.25) + 0.18 * math.sin(2.0 * a)
    glow = 0.5 + 0.5 * math.sin(a - 0.35)
    return local_x, local_y, angle, glow


def time_glide_states(phase: float) -> tuple[MotifState, ...]:
    """Two states obeying mirror + half-period translation.

    If ``G`` mirrors x and swaps the two colors, then
    ``G(states(t)) == states(t + 1/2)``.
    """

    lx, ly, angle, glow = _seed_pose(phase)
    left = MotifState(
        orbit=0,
        x=-0.43 + lx,
        y=ly,
        angle=angle,
        scale=1.0,
        color=0,
        chirality=1,
        glow=glow,
    )

    # The right motif is the mirrored seed half a period earlier.
    rx, ry, rangle, rglow = _seed_pose(phase - 0.5)
    right = MotifState(
        orbit=1,
        x=0.43 - rx,
        y=ry,
        angle=math.pi - rangle,
        scale=1.0,
        color=1,
        chirality=-1,
        glow=rglow,
    )
    return left, right


def time_screw_states(phase: float, order: int = 4) -> tuple[MotifState, ...]:
    """An order-n rotation combined with a 1/n time translation."""

    if order not in (3, 4, 6):
        raise ValueError("time screw order must be 3, 4, or 6")

    result: list[MotifState] = []
    radius = 0.49 if order <= 4 else 0.53
    for j in range(order):
        local_phase = phase - j / order
        dx, dy, seed_angle, glow = _seed_pose(local_phase)
        # The seed lives near the positive x axis.  Rotate its entire pose into
        # the j-th sector; adjacent sectors carry adjacent phase colors.
        qx = radius + dx
        qy = 0.78 * dy
        rotation = TAU * j / order
        cos_r = math.cos(rotation)
        sin_r = math.sin(rotation)
        x = cos_r * qx - sin_r * qy
        y = sin_r * qx + cos_r * qy
        result.append(
            MotifState(
                orbit=j,
                x=x,
                y=y,
                angle=seed_angle + rotation,
                scale=0.92 if order == 6 else 1.0,
                color=j,
                chirality=1,
                glow=glow,
            )
        )
    return tuple(result)


def diagonal_relay_states(phase: float, order: int = 3) -> tuple[MotifState, ...]:
    """A diagonal subgroup generated by one cell step + a 1/n time shift.

    Space is a circle of length 2 with an n-cell supercell.  Translation by a
    single cell and a 1/n time shift are not symmetries separately; their
    diagonal combination is.
    """

    if order < 2:
        raise ValueError("relay order must be at least 2")

    cell_width = 2.0 / order
    first_center = -1.0 + 0.5 * cell_width
    result: list[MotifState] = []
    for j in range(order):
        local_phase = phase - j / order
        dx, dy, seed_angle, glow = _seed_pose(local_phase)
        center = first_center + j * cell_width
        result.append(
            MotifState(
                orbit=j,
                x=center + 0.85 * dx,
                y=1.65 * dy,
                angle=seed_angle + 0.22 * math.sin(TAU * local_phase),
                scale=1.08,
                color=j,
                chirality=1,
                glow=glow,
            )
        )
    return tuple(result)


def mixed_time_glide_states(phase: float) -> tuple[MotifState, ...]:
    """Reflection + half-y translation + half-period translation.

    On the spatial torus the generator is
    ``G(x, y, t) = (-x, y + 1, t + 1/2)``.
    """

    dx, dy, angle, glow = _seed_pose(phase)
    seed = MotifState(
        orbit=0,
        x=-0.42 + dx,
        y=-0.48 + 0.82 * dy,
        angle=angle,
        scale=0.96,
        color=0,
        chirality=1,
        glow=glow,
    )

    dx, dy, angle, glow = _seed_pose(phase - 0.5)
    partner = MotifState(
        orbit=1,
        x=0.42 - dx,
        y=wrap_coordinate(-0.48 + 0.82 * dy + 1.0),
        angle=math.pi - angle,
        scale=0.96,
        color=1,
        chirality=-1,
        glow=glow,
    )
    return seed, partner


def glide_time_reversal_states(phase: float) -> tuple[MotifState, ...]:
    """Half-cell translation coupled to playback reversal.

    ``Q(x, y, t) = (x + 1, y, -t)`` on the x torus.  The two motifs traverse
    the same orbit in opposite time directions.
    """

    dx, dy, angle, glow = _seed_pose(phase)
    forward = MotifState(
        orbit=0,
        x=-0.50 + 0.82 * dx,
        y=1.55 * dy,
        angle=angle,
        scale=1.02,
        color=0,
        glow=glow,
    )

    dx, dy, angle, glow = _seed_pose(-phase)
    rewind = MotifState(
        orbit=1,
        x=0.50 + 0.82 * dx,
        y=1.55 * dy,
        angle=angle,
        scale=1.02,
        color=1,
        glow=glow,
    )
    return forward, rewind


def rotary_time_reversal_states(phase: float) -> tuple[MotifState, ...]:
    """The magnetic point group 4': quarter-turn coupled to t -> -t.

    Opposite motifs share a pose, so the square of the mixed generator is the
    instantaneous pure half-turn.  Adjacent motifs play the seed in opposite
    directions.  The two-color action is the quotient C4 -> C2.
    """

    result: list[MotifState] = []
    radius = 0.49
    for j in range(4):
        local_phase = phase if j % 2 == 0 else -phase
        dx, dy, seed_angle, glow = _seed_pose(local_phase)
        qx = radius + dx
        qy = 0.78 * dy
        rotation = TAU * j / 4.0
        cos_r = math.cos(rotation)
        sin_r = math.sin(rotation)
        result.append(
            MotifState(
                orbit=j,
                x=cos_r * qx - sin_r * qy,
                y=sin_r * qx + cos_r * qy,
                angle=seed_angle + rotation,
                scale=1.0,
                color=j % 2,
                glow=glow,
            )
        )
    return tuple(result)


def dihedral_choreography_states(phase: float) -> tuple[MotifState, ...]:
    """A diagonal D3 generated by a time screw and mirror/time reversal.

    The reversible seed obeys ``m_y(seed(t)) = seed(-t)``.  Its three rotated,
    phase-shifted copies obey both ``S=(R_120, t+1/3)`` and
    ``M=(m_y, t->-t)``, with ``M S M = S^-1``.
    """

    result: list[MotifState] = []
    for j in range(3):
        local_phase = wrap_phase(phase - j / 3.0)
        a = TAU * local_phase
        qx = 0.49 + 0.075 * math.cos(a) + 0.015 * math.cos(2.0 * a)
        qy = 0.095 * math.sin(a) + 0.018 * math.sin(2.0 * a)
        seed_angle = 0.48 * math.sin(a) + 0.12 * math.sin(2.0 * a)
        glow = 0.5 + 0.5 * math.cos(a)
        rotation = TAU * j / 3.0
        cos_r = math.cos(rotation)
        sin_r = math.sin(rotation)
        result.append(
            MotifState(
                orbit=j,
                x=cos_r * qx - sin_r * qy,
                y=sin_r * qx + cos_r * qy,
                angle=seed_angle + rotation,
                scale=1.02,
                color=j,
                chirality=1,
                glow=glow,
                glyph="dart",
            )
        )
    return tuple(result)


def reflect_x(state: MotifState, order: int = 2) -> MotifState:
    """Apply the colored spatial part of the time-glide generator."""

    return MotifState(
        orbit=(state.orbit + 1) % order,
        x=-state.x,
        y=state.y,
        angle=math.pi - state.angle,
        scale=state.scale,
        color=(state.color + 1) % order,
        chirality=-state.chirality,
        glow=state.glow,
        glyph=state.glyph,
    )


def rotate(state: MotifState, order: int) -> MotifState:
    """Apply one colored spatial step of an order-n screw."""

    rotation = TAU / order
    cos_r = math.cos(rotation)
    sin_r = math.sin(rotation)
    return MotifState(
        orbit=(state.orbit + 1) % order,
        x=cos_r * state.x - sin_r * state.y,
        y=sin_r * state.x + cos_r * state.y,
        angle=state.angle + rotation,
        scale=state.scale,
        color=(state.color + 1) % order,
        chirality=state.chirality,
        glow=state.glow,
        glyph=state.glyph,
    )


def translate_cell(state: MotifState, order: int) -> MotifState:
    """Apply one colored cell translation on the relay's spatial torus."""

    return MotifState(
        orbit=(state.orbit + 1) % order,
        x=wrap_coordinate(state.x + 2.0 / order),
        y=state.y,
        angle=state.angle,
        scale=state.scale,
        color=(state.color + 1) % order,
        chirality=state.chirality,
        glow=state.glow,
        glyph=state.glyph,
    )


def mixed_time_glide_step(state: MotifState) -> MotifState:
    """Apply ``(x,y)->(-x,y+1)`` and the C2 color swap."""

    return MotifState(
        orbit=(state.orbit + 1) % 2,
        x=-state.x,
        y=wrap_coordinate(state.y + 1.0),
        angle=math.pi - state.angle,
        scale=state.scale,
        color=(state.color + 1) % 2,
        chirality=-state.chirality,
        glow=state.glow,
        glyph=state.glyph,
    )


def glide_time_reversal_step(state: MotifState) -> MotifState:
    """Apply the half-cell spatial part and C2 color swap of glide TR."""

    return MotifState(
        orbit=(state.orbit + 1) % 2,
        x=wrap_coordinate(state.x + 1.0),
        y=state.y,
        angle=state.angle,
        scale=state.scale,
        color=(state.color + 1) % 2,
        chirality=state.chirality,
        glow=state.glow,
        glyph=state.glyph,
    )


def rotary_time_reversal_step(state: MotifState) -> MotifState:
    """Apply the spatial/color part of the 4' generator."""

    rotation = math.pi / 2.0
    return MotifState(
        orbit=(state.orbit + 1) % 4,
        x=-state.y,
        y=state.x,
        angle=state.angle + rotation,
        scale=state.scale,
        color=(state.color + 1) % 2,
        chirality=state.chirality,
        glow=state.glow,
        glyph=state.glyph,
    )


def dihedral_reflection_step(state: MotifState) -> MotifState:
    """Apply y reflection and the color transposition (1 2)."""

    return MotifState(
        orbit=(-state.orbit) % 3,
        x=state.x,
        y=-state.y,
        angle=-state.angle,
        scale=state.scale,
        color=(-state.color) % 3,
        # The dart glyph is mirror-symmetric about its local x axis.
        chirality=state.chirality,
        glow=state.glow,
        glyph=state.glyph,
    )


def sorted_states(states: Sequence[MotifState]) -> tuple[MotifState, ...]:
    return tuple(sorted(states, key=lambda state: state.orbit))


EXAMPLES: dict[str, SymmetrySpec] = {
    "time_glide": SymmetrySpec(
        key="time_glide",
        title="C2 time glide",
        sampling_order=2,
        phase_shift=0.5,
        spatial_action="reflection x -> -x",
        color_permutation=(1, 0),
        state_function=time_glide_states,
    ),
    "time_screw": SymmetrySpec(
        key="time_screw",
        title="C4 time screw",
        sampling_order=4,
        phase_shift=0.25,
        spatial_action="rotation by 90 degrees",
        color_permutation=(1, 2, 3, 0),
        state_function=lambda phase: time_screw_states(phase, order=4),
    ),
    "diagonal_relay": SymmetrySpec(
        key="diagonal_relay",
        title="C3 diagonal spacetime relay",
        sampling_order=3,
        phase_shift=1.0 / 3.0,
        spatial_action="translation by one cell on a three-cell torus",
        color_permutation=(1, 2, 0),
        state_function=lambda phase: diagonal_relay_states(phase, order=3),
    ),
    "mixed_time_glide": SymmetrySpec(
        key="mixed_time_glide",
        title="Mixed space-time glide",
        sampling_order=2,
        phase_shift=0.5,
        spatial_action="x reflection plus half-cell y translation",
        color_permutation=(1, 0),
        state_function=mixed_time_glide_states,
    ),
    "glide_time_reversal": SymmetrySpec(
        key="glide_time_reversal",
        title="Glide time reversal",
        sampling_order=2,
        phase_shift=0.0,
        spatial_action="half-cell x translation",
        color_permutation=(1, 0),
        state_function=glide_time_reversal_states,
        temporal_action="time reversal t -> -t",
    ),
    "rotary_time_reversal": SymmetrySpec(
        key="rotary_time_reversal",
        title="4-prime rotary time reversal",
        sampling_order=4,
        phase_shift=0.0,
        spatial_action="rotation by 90 degrees",
        color_permutation=(1, 0),
        state_function=rotary_time_reversal_states,
        temporal_action="time reversal t -> -t",
    ),
    "dihedral_choreography": SymmetrySpec(
        key="dihedral_choreography",
        title="D3 dihedral choreography",
        sampling_order=3,
        phase_shift=1.0 / 3.0,
        spatial_action="120-degree rotation and an independent mirror",
        color_permutation=(1, 2, 0),
        state_function=dihedral_choreography_states,
        temporal_action="phase translation plus time reversal",
    ),
}
