#!/usr/bin/env python3
"""Generate the 3x3 torus mini-tutorial page.

The ambient group is the discrete torus A = (Z/3)^2 acting on itself by
translation.  Its six subgroups are computed here, together with the three
independent ways of naming each one used across this project:

  1. as a stabilizer / equivalence relation  -- Stab(P) for a coloured pattern
  2. by generators and relations             -- a presentation
  3. in Chaim Goodman-Strauss's notation     -- the colour signature and type

Run with --check to verify the committed page is current.
"""

from __future__ import annotations

import argparse
import sys
from html import escape
from itertools import product
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAGE = ROOT / "torus-tutorial.html"

N = 3
CELLS = [(a, b) for a in range(N) for b in range(N)]

# Okabe-Ito, extended to nine entries for the free colouring.
PALETTE = ["#0072B2", "#E69F00", "#009E73", "#CC79A7", "#56B4E9",
           "#D55E00", "#8C7BB0", "#B4A16B", "#6C7A89"]
LABELS = "ABCDEFGHI"


def span(generators: tuple[tuple[int, int], ...]) -> frozenset[tuple[int, int]]:
    seen = {(0, 0)}
    frontier = [(0, 0)]
    while frontier:
        x = frontier.pop()
        for g in generators:
            y = ((x[0] + g[0]) % N, (x[1] + g[1]) % N)
            if y not in seen:
                seen.add(y)
                frontier.append(y)
    return frozenset(seen)


def cosets(subgroup: frozenset[tuple[int, int]]) -> dict[tuple[int, int], int]:
    """Cell -> coset index, with the coset of the origin numbered zero."""

    assigned: dict[tuple[int, int], int] = {}
    index = 0
    for cell in CELLS:
        if cell in assigned:
            continue
        for k in subgroup:
            assigned[((cell[0] + k[0]) % N, (cell[1] + k[1]) % N)] = index
        index += 1
    return assigned


def order_of(element: tuple[int, int]) -> int:
    steps, current = 1, element
    while current != (0, 0):
        current = ((current[0] + element[0]) % N, (current[1] + element[1]) % N)
        steps += 1
    return steps


# ---------------------------------------------------------------------------
# The six subgroups.  X = (1,0) shifts the row, Y = (0,1) shifts the column.

SUBGROUPS: tuple[dict[str, object], ...] = (
    {
        "key": "full",
        "generators": ((1, 0), (0, 1)),
        "generator_words": "X, Y",
        "name": "K = A",
        "shape": "the whole torus",
        "invariant": "none — every cell is equivalent to every other",
        "pattern": "the constant pattern: one colour everywhere",
        "added": "X = 1, Y = 1",
        "quotient": "trivial group",
        "long_signature": "◦<sup>1,1</sup>",
        "colour_type": "◦",
    },
    {
        "key": "rows",
        "generators": ((0, 1),),
        "generator_words": "Y",
        "name": "K = ⟨Y⟩",
        "shape": "rows",
        "invariant": "a mod 3 — the row index",
        "pattern": "three horizontal stripes",
        "added": "Y = 1",
        "quotient": "C₃, generated by the image of X",
        "long_signature": "◦<sup>(ABC), 1</sup>",
        "colour_type": "◦³/◦",
    },
    {
        "key": "columns",
        "generators": ((1, 0),),
        "generator_words": "X",
        "name": "K = ⟨X⟩",
        "shape": "columns",
        "invariant": "b mod 3 — the column index",
        "pattern": "three vertical stripes",
        "added": "X = 1",
        "quotient": "C₃, generated by the image of Y",
        "long_signature": "◦<sup>1, (ABC)</sup>",
        "colour_type": "◦³/◦",
    },
    {
        "key": "diagonal",
        "generators": ((1, 1),),
        "generator_words": "XY",
        "name": "K = ⟨XY⟩",
        "shape": "the diagonal",
        "invariant": "(b − a) mod 3",
        "pattern": "three diagonal stripes, leaning one way",
        "added": "XY = 1, so Y = X⁻¹",
        "quotient": "C₃, generated by the image of X",
        "long_signature": "◦<sup>(ACB), (ABC)</sup>",
        "colour_type": "◦³/◦",
    },
    {
        "key": "antidiagonal",
        "generators": ((1, 2),),
        "generator_words": "XY²",
        "name": "K = ⟨XY²⟩",
        "shape": "the anti-diagonal",
        "invariant": "(a + b) mod 3",
        "pattern": "three diagonal stripes, leaning the other way",
        "added": "XY² = 1, so X = Y",
        "quotient": "C₃, generated by the common image of X and Y",
        "long_signature": "◦<sup>(ABC), (ABC)</sup>",
        "colour_type": "◦³/◦",
    },
    {
        "key": "trivial",
        "generators": (),
        "generator_words": "— (empty)",
        "name": "K = {0}",
        "shape": "a single cell",
        "invariant": "the cell itself — nothing is identified",
        "pattern": "nine distinct colours, no repetition",
        "added": "nothing",
        "quotient": "C₃ × C₃, the whole torus",
        "long_signature": "◦<sup>(ABC…), (ADG…)</sup>",
        "colour_type": "◦⁹/◦",
    },
)


def build_records() -> list[dict[str, object]]:
    records = []
    for spec in SUBGROUPS:
        subgroup = span(tuple(spec["generators"]))          # type: ignore[arg-type]
        blocks = cosets(subgroup)
        colours = len(set(blocks.values()))
        rho_x = order_of((1, 0)) if (1, 0) not in subgroup else 1
        rho_y = order_of((0, 1)) if (0, 1) not in subgroup else 1
        records.append({
            **spec,
            "subgroup": subgroup,
            "blocks": blocks,
            "size": len(subgroup),
            "index": 9 // len(subgroup),
            "colours": colours,
            "short_signature": f"◦<sup>{rho_x},{rho_y}</sup>",
        })
    return records


def validate(records: list[dict[str, object]]) -> None:
    seen = set()
    for record in records:
        subgroup = record["subgroup"]
        assert isinstance(subgroup, frozenset)
        if subgroup in seen:
            raise ValueError(f"duplicate subgroup for {record['key']}")
        seen.add(subgroup)
        for x in subgroup:
            for y in subgroup:
                if ((x[0] + y[0]) % N, (x[1] + y[1]) % N) not in subgroup:
                    raise ValueError(f"{record['key']} is not closed")
        if record["colours"] != record["index"]:
            raise ValueError(f"{record['key']}: colours must equal the index")
        if 9 % len(subgroup):
            raise ValueError(f"{record['key']}: Lagrange violated")
    if len(seen) != 6:
        raise ValueError(f"expected 6 subgroups, found {len(seen)}")


# ---------------------------------------------------------------------------

def grid_svg(record: dict[str, object], cell: int = 44, gap: int = 4) -> str:
    blocks = record["blocks"]
    subgroup = record["subgroup"]
    size = N * cell + (N - 1) * gap
    parts = [
        f'<svg class="torus-grid" viewBox="0 0 {size} {size}" width="{size}" '
        f'height="{size}" role="img" aria-label="'
        f'{escape(str(record["colours"]))} colour classes on the three by three torus">'
    ]
    for (a, b), block in sorted(blocks.items()):
        x, y = b * (cell + gap), a * (cell + gap)
        parts.append(
            f'<rect x="{x}" y="{y}" width="{cell}" height="{cell}" rx="5" '
            f'fill="{PALETTE[block]}"/>'
        )
        parts.append(
            f'<text x="{x + cell / 2}" y="{y + cell / 2 + 5}" text-anchor="middle" '
            f'font-size="15" font-weight="700" fill="#fffaf1">{LABELS[block]}</text>'
        )
        if (a, b) in subgroup:
            parts.append(
                f'<circle cx="{x + cell / 2}" cy="{y + cell / 2}" r="{cell / 2 - 4}" '
                f'fill="none" stroke="#fffaf1" stroke-width="2.4" opacity="0.9"/>'
            )
    parts.append("</svg>")
    return "".join(parts)


def tiled_svg(record: dict[str, object], cell: int = 17, gap: int = 2) -> str:
    blocks = record["blocks"]
    span_n = 2 * N
    size = span_n * cell + (span_n - 1) * gap
    parts = [
        f'<svg class="torus-tile" viewBox="0 0 {size} {size}" width="{size}" '
        f'height="{size}" role="img" aria-label="the same colouring tiled two by two">'
    ]
    for a in range(span_n):
        for b in range(span_n):
            block = blocks[(a % N, b % N)]
            parts.append(
                f'<rect x="{b * (cell + gap)}" y="{a * (cell + gap)}" width="{cell}" '
                f'height="{cell}" rx="2" fill="{PALETTE[block]}"/>'
            )
    parts.append("</svg>")
    return "".join(parts)


def card(record: dict[str, object]) -> str:
    return f"""
    <article class="subgroup-card" id="k-{record['key']}">
      <header class="card-head">
        <h3>{record['name']}</h3>
        <p class="card-shape">{escape(str(record['shape']))}</p>
        <p class="card-meta"><span>|K| = {record['size']}</span>
          <span>index {record['index']}</span>
          <span>{record['colours']} colour{'s' if record['colours'] != 1 else ''}</span></p>
      </header>
      <div class="card-art">
        {grid_svg(record)}
        <div class="tile-wrap">{tiled_svg(record)}
          <span class="tile-caption">tiled 2&times;2</span></div>
      </div>
      <dl class="card-data">
        <dt>1 &middot; As a stabilizer</dt>
        <dd>The translations fixing <em>{escape(str(record['pattern']))}</em>.
            As an equivalence relation on cells: same class when
            <code>{escape(str(record['invariant']))}</code> agrees.</dd>

        <dt>2 &middot; By generators</dt>
        <dd><code>K = &#10216;{escape(str(record['generator_words']))}&#10217;</code>.
            Imposing <code>{escape(str(record['added']))}</code> on the ambient
            presentation gives the colour group
            <code>A/K = {escape(str(record['quotient']))}</code>.</dd>

        <dt>3 &middot; Chaim notation</dt>
        <dd>Short signature {record['short_signature']}, long form
            {record['long_signature']}, colour type
            <strong>{record['colour_type']}</strong>.</dd>
      </dl>
    </article>"""


STYLE = """
  :root { --ink:#1b2430; --muted:#5a6470; --paper:#faf8f2; --rule:#ded8c9;
          --card:#ffffff; --accent:#0072B2; }
  body { background:var(--paper); color:var(--ink); }
  .tutorial { max-width:1120px; margin:0 auto; padding:0 20px 72px; }
  .tutorial h1 { font-size:2rem; line-height:1.2; margin:.2em 0 .3em; }
  .tutorial h2 { font-size:1.32rem; margin:2.4rem 0 .7rem;
                 border-bottom:1px solid var(--rule); padding-bottom:.35rem; }
  .tutorial h3 { font-size:1.05rem; margin:0 0 .15rem; }
  .overline { text-transform:uppercase; letter-spacing:.12em; font-size:.74rem;
              color:var(--muted); margin:2rem 0 0; }
  .lead { font-size:1.05rem; color:var(--muted); max-width:62ch; }
  .tutorial p, .tutorial li { max-width:74ch; }
  code { background:#eef1f4; padding:.08em .34em; border-radius:4px;
         font-size:.92em; }
  .ways { display:grid; gap:14px;
          grid-template-columns:repeat(auto-fit,minmax(min(260px,100%),1fr));
          margin:1rem 0 0; padding:0; list-style:none; }
  .ways li { background:var(--card); border:1px solid var(--rule); border-radius:10px;
             padding:14px 16px; }
  .ways strong { display:block; margin-bottom:.25rem; }
  .subgroup-grid { display:grid; gap:18px;
                   grid-template-columns:repeat(auto-fit,minmax(min(330px,100%),1fr)); }
  .subgroup-card { background:var(--card); border:1px solid var(--rule);
                   border-radius:12px; padding:16px 18px 6px; }
  .card-head h3 { font-family:ui-monospace,Menlo,Consolas,monospace; }
  .card-shape { margin:.1rem 0 .3rem; color:var(--muted); font-size:.92rem; }
  .card-meta { margin:0 0 .8rem; font-size:.78rem; color:var(--muted); }
  .card-meta span { display:inline-block; background:#eef1f4; border-radius:20px;
                    padding:.14em .7em; margin-right:.3em; }
  .card-art { display:flex; align-items:flex-start; gap:16px; flex-wrap:wrap;
              margin-bottom:.6rem; }
  .torus-grid, .torus-tile { max-width:100%; height:auto; }
  .tile-wrap { display:flex; flex-direction:column; gap:5px; }
  .tile-caption { font-size:.68rem; color:var(--muted); }
  .card-data { margin:0; }
  .card-data dt { font-size:.76rem; text-transform:uppercase; letter-spacing:.08em;
                  color:var(--accent); margin-top:.7rem; }
  .card-data dd { margin:.2rem 0 0; font-size:.9rem; }
  .table-scroll { overflow-x:auto; }
  table { border-collapse:collapse; font-size:.9rem; min-width:520px; }
  th, td { text-align:left; padding:.42em .8em; border-bottom:1px solid var(--rule); }
  th { font-size:.76rem; text-transform:uppercase; letter-spacing:.07em;
       color:var(--muted); }
  .footnote { color:var(--muted); font-size:.86rem; }
  @media (prefers-color-scheme: dark) {
    :root { --ink:#e8e6e1; --muted:#a8b0ba; --paper:#161a1f; --rule:#333a42;
            --card:#1e242b; --accent:#56B4E9; }
    code { background:#2a323a; }
    .card-meta span { background:#2a323a; }
  }
"""


def build_page() -> str:
    records = build_records()
    validate(records)
    cards = "".join(card(record) for record in records)
    rows = "".join(
        f"<tr><td><code>{escape(str(r['name']))}</code></td>"
        f"<td>{escape(str(r['shape']))}</td><td>{r['index']}</td>"
        f"<td>{r['colours']}</td><td>{r['short_signature']}</td>"
        f"<td>{r['colour_type']}</td></tr>"
        for r in records
    )
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="A mini-tutorial: the six subgroups of the 3x3 discrete torus, each named three ways — as a stabilizer, by generators, and in Chaim Goodman-Strauss's colour notation.">
  <meta name="theme-color" content="#ffffff">
  <title>The 3×3 torus: three ways to name a group</title>
  <link rel="icon" href="favicon.svg" type="image/svg+xml">
  <link rel="stylesheet" href="site-controls-v2.css">
  <style>{STYLE}</style>
</head>
<body>
  <a class="skip-link" href="#tutorial">Skip to tutorial</a>
  <header class="site-header">
    <div class="header-inner">
      <a class="site-name" href="./">Spacetime-group visualizations</a>
      <nav aria-label="Project links">
        <a href="./">Gallery</a>
        <a href="future-directions.html">Colours</a>
        <a href="color-pattern-catalog.html">Patterns</a>
        <a href="clockwork-coloring-correspondence.html">Clockwork</a>
        <a href="space-group-correspondence.html">Space groups</a>
        <a href="torus-tutorial.html" aria-current="page">Torus tutorial</a>
        <a href="docs/orbifold_notation.html">Notation</a>
        <a href="https://github.com/yaroslavvb/animated-groups">Source</a>
      </nav>
    </div>
  </header>

  <main id="tutorial" class="tutorial">
    <p class="overline">Mini-tutorial · finite ambient group</p>
    <h1>The 3&times;3 torus: three ways to name a group</h1>
    <p class="lead">
      The smallest setting where colour symmetry is completely computable. The ambient group
      has nine elements, it has exactly six subgroups, and every subgroup can be named three
      independent ways — as the stabilizer of a pattern, by a presentation, and in the
      colour notation of <cite>The Symmetries of Things</cite>. All three agree.
    </p>

    <h2>The ambient group</h2>
    <p>
      Take a 3&times;3 grid that wraps in both directions and let it act on itself by translation.
      Writing <code>X</code> for &ldquo;shift one row&rdquo; and <code>Y</code> for
      &ldquo;shift one column&rdquo;:
    </p>
    <p><code>A = &#10216; X, Y | X&sup3; = Y&sup3; = 1, XY = YX &#10217; = (&#8484;/3)&sup2;</code>, of order&nbsp;9.</p>
    <p>
      This is the finite version of the handle symbol <code>&#9702;</code> from Chapter&nbsp;10 of
      <cite>The Symmetries of Things</cite>, whose reduced annotation is
      <code>&#9702;<sub>X,Y</sub></code> with the single relation <code>XY = YX</code>. The torus
      adds <code>X&sup3; = Y&sup3; = 1</code>. Because <code>A</code> is abelian, every subgroup is
      normal, so every quotient is a group and every colour group is <em>regular</em>: the number
      of colours is exactly the index.
    </p>

    <h2>Three ways to name the same group</h2>
    <ul class="ways">
      <li><strong>1 &middot; As a stabilizer</strong>
        Choose a coloured pattern and keep the translations that leave it unchanged. Equivalently,
        an equivalence relation on cells that is invariant under translation. The two are the same
        data: the subgroup is the class of the identity, and the classes are its cosets.</li>
      <li><strong>2 &middot; By generators</strong>
        Give generators and relations. Imposing the extra relations that kill <code>K</code> turns
        the ambient presentation into a presentation of the <em>colour group</em>
        <code>A/K</code> — relations describe the quotient, never the subgroup.</li>
      <li><strong>3 &middot; Chaim notation</strong>
        Replace each generator in the signature by the colour permutation it induces. The short
        form keeps only the <em>order</em> of that permutation; the type <code>G/K</code> records
        the full group and the kernel.</li>
    </ul>

    <h2>The six subgroups</h2>
    <p>
      Cells are filled by their coset of <code>K</code>, which is exactly the colour class. Ringed
      cells are <code>K</code> itself. The number of distinct letters is the index, which is the
      number of colours.
    </p>
    <div class="subgroup-grid">{cards}
    </div>

    <h2>Summary</h2>
    <div class="table-scroll">
      <table>
        <thead><tr><th>subgroup</th><th>shape</th><th>index</th><th>colours</th>
          <th>short signature</th><th>colour type</th></tr></thead>
        <tbody>{rows}</tbody>
      </table>
    </div>
    <p class="footnote">
      Three subgroups share the short signature <code>&#9702;<sup>3,3</sup></code>. The short form
      records only permutation <em>orders</em>, so it cannot separate them — the long form and
      the colour group can. This is the same lossiness that forces Conway to print
      <code>&#8727;<sup>(AB)</sup>3<sup>(BC)</sup>3<sup>(CA)</sup>3</code> in full for
      <code>&#8727;333&sup3;//&#9702;</code>.
    </p>

    <h2>Six subgroups, three types</h2>
    <p>
      <code>Aut(A) = GL(2,&#120125;&#8323;)</code> has order 48 and acts on the six subgroups with
      three orbits: the trivial subgroup, the four lines, and the whole torus. The four lines are
      one orbit — one line for each slope <code>0, 1, 2, &infin;</code> — which is
      Conway&rsquo;s count of <code>p&nbsp;+&nbsp;1</code> subgroups of index <code>p</code>.
      You can see the group acting: transposing swaps rows and columns, and shearing carries
      columns to each diagonal in turn.
    </p>
    <p>
      There is no two-colour entry anywhere on this page, and the reason is arithmetic: a colour
      group must have order dividing 9, and <code>2 &#8740; 9</code>. Equivalently, no pattern on
      this torus has a colour-swapping symmetry, since the two classes would have to be the same
      size.
    </p>

    <h2>Where this sits</h2>
    <p>
      Lifting to the plane, every one of these six kernels is a lattice, so every colour type here
      is <code>&#9702;</code> with some number of colours — the family at the top of the
      <a href="color-pattern-catalog.html">periodic colour-pattern catalog</a>. The torus
      classification is <em>finer</em> than the wallpaper one: fixing a finite ambient removes the
      ability to rescale, so index matters where affine equivalence would forget it.
    </p>
    <p class="footnote">
      Generated by <a href="https://github.com/yaroslavvb/animated-groups/blob/main/scripts/generate_torus_tutorial.py">scripts/generate_torus_tutorial.py</a>.
      Notation follows Conway, Burgiel and Goodman-Strauss, <cite>The Symmetries of Things</cite>,
      Chapters 10&ndash;13.
    </p>
  </main>
</body>
</html>
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify the committed page matches this generator")
    args = parser.parse_args()

    page = build_page()
    if args.check:
        if not PAGE.exists() or PAGE.read_text(encoding="utf-8") != page:
            print(f"stale: {PAGE.relative_to(ROOT)}")
            return 1
        print("torus tutorial is current")
        return 0
    PAGE.write_text(page, encoding="utf-8")
    print(f"wrote {PAGE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
